version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: housing-chatbot:latest
    container_name: housing-chatbot-app
    environment:
      BACKEND_URL: http://localhost:8000/chat
      ELASTICSEARCH_URL: http://elasticsearch:9200
      SCRAPER_RUN_ON_START: "1"
      REINDEX_ON_START: "1"
    ports:
      - "8000:8000"
      - "8501:8501"
    depends_on:
      - elasticsearch
    volumes:
      - .:/app

  elasticsearch:
    image: elasticsearch:9.4.2
    container_name: es_local
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
